name: keyhelp
description: 个人自用的安卓轻量化自动化工具
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 状态管理
  flutter_riverpod: ^2.6.1
  
  # 本地存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # 权限管理
  permission_handler: ^11.3.1
  
  # 定时任务
  flutter_local_notifications: ^17.2.3
  
  # UI组件
  flutter_animate: ^4.5.0
  
  # 工具类
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
